version: '3.6'

services:

  # Backend API
  facerecognitionbrain-api-docker:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/facerecognitionbrain-api-docker
    environment:
      POSTGRES_URI: postgres://sally:secret@postgres:5432/facerecognitionbrain-api-docker-docker
      REDIS_URI: redis://redis:6379
    ports:
      - "3000:3000"
    volumes: 
      - ./:/usr/src/facerecognitionbrain-api-docker

  # Postgres
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_URL: postgres://sally:secret@localhost:5432/facerecognitionbrain-api-docker-docker
      POSTGRES_DB: facerecognitionbrain-api-docker-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"